version: "3.8"
services: 
  dev-server:
    container_name: da-server
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    restart: always
    command: npm run dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5500:5500
    networks:
      - server-db-network
    depends_on:
      dev-db:
        condition: service_healthy

  dev-db:
    container_name: da-db
    image: mongo
    restart: always
    expose:
      - 27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - server-db-network
    volumes:
      - mongodb_data:/data/db

networks:
  server-db-network:
    driver: bridge