version: "3.8"
services: 
  server:
    container_name: da-dev-server
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    restart: always
    command: npm run dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5500:5500
    networks:
      - server-db

  db:
    image: mongo
    restart: always
    expose:
      - 27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - server-db

volumes:
  db-data:

networks:
  server-db: