version: '3.8'

services:
  server:
    container_name: da-server
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - 5500:5500
    depends_on:
      db:
        condition: service_healthy
    networks:
      - server-db-network
  
  db:
    image: mongo
    container_name: da-db
    restart: always
    expose:
      - 27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - server-db-network

networks:
  server-db-network:
    driver: bridge

volumes:
  db-data:
